/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jd/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Job Description */
        post: operations["extract_job_description_api_v1_jd_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EducationInfo */
        EducationInfo: {
            /**
             * Minimum Degree
             * @description The lowest acceptable degree (e.g., 'B.Tech', 'Bachelor\'s', 'Master\'s'). Return 'Not Specified' if missing.
             * @default Not Specified
             */
            minimum_degree: string | null;
            /**
             * Preferred Fields
             * @description Preferred fields of study (e.g., 'Computer Science', 'Information Technology').
             */
            preferred_fields?: string[];
        };
        /** ExperienceInfo */
        ExperienceInfo: {
            /**
             * Min Years
             * @description Minimum years of experience required. Strictly return 0.0 if for freshers or entry-level.
             * @default 0
             */
            min_years: number;
            /**
             * Max Years
             * @description Maximum years of experience mentioned. Leave null if not mentioned.
             */
            max_years?: number | null;
            /**
             * Is Fresher Allowed
             * @description True ONLY if the JD explicitly mentions freshers, graduates, or 0 years experience.
             * @default false
             */
            is_fresher_allowed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Api Key Configured */
            api_key_configured: boolean;
            /** Server Region */
            server_region: string;
        };
        /** JDExtractionModel */
        JDExtractionModel: {
            /**
             * Job Title
             * @description The exact title of the job role if explicitly mentioned. If NOT mentioned, analyze the entire JD and infer a highly relevant and standard professional job title (e.g., 'Senior Frontend Developer', 'Backend Engineer').
             */
            job_title: string;
            /**
             * Company Name
             * @description Name of the hiring company. Return 'Not Specified' if missing.
             * @default Not Specified
             */
            company_name: string | null;
            /**
             * Location
             * @description Job location (City, State, Country, or 'Remote'). Return 'Not Specified' if missing.
             * @default Not Specified
             */
            location: string | null;
            /**
             * Employment Type
             * @description Classify the employment type strictly into one of the allowed categories.
             * @default Not Specified
             * @enum {string}
             */
            employment_type: "Full-time" | "Part-time" | "Contract" | "Internship" | "Freelance" | "Not Specified";
            /**
             * Department
             * @description Department or team name if mentioned (e.g., 'Engineering', 'Marketing').
             * @default Not Specified
             */
            department: string | null;
            experience: components["schemas"]["ExperienceInfo"];
            skills: components["schemas"]["SkillSet"];
            education: components["schemas"]["EducationInfo"];
            /**
             * Key Responsibilities
             * @description Extract ALL distinct day-to-day responsibilities or tasks explicitly stated in the JD. DO NOT make up or hallucinate tasks. If only 1 or 2 are mentioned, return only those.
             */
            key_responsibilities?: string[];
            /**
             * Ats Keywords
             * @description Extract a comprehensive list of crucial keywords for ATS optimization. Include highly repeated terms, core technologies, and key domain phrases present in the text.
             */
            ats_keywords?: string[];
        };
        /** JobDescriptionRequest */
        JobDescriptionRequest: {
            /** Raw Text */
            raw_text: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SkillSet */
        SkillSet: {
            /**
             * Must Have Tech Skills
             * @description Strict mandatory technical tools, programming languages, or frameworks (e.g., 'React', 'Python', 'Docker'). Extract ONLY from the JD.
             */
            must_have_tech_skills?: string[];
            /**
             * Nice To Have Tech Skills
             * @description Bonus, preferred, or 'nice to have' technical skills mentioned. Do not infer; extract only what is written.
             */
            nice_to_have_tech_skills?: string[];
            /**
             * Soft Skills
             * @description Behavioral skills explicitly mentioned (e.g., 'Communication', 'Leadership', 'Agile').
             */
            soft_skills?: string[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    extract_job_description_api_v1_jd_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobDescriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDExtractionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
